-- Run this migration after the exercises table has been created
-- Seed basic exercise data
INSERT INTO exercises (name, description, category, muscle_group, equipment, difficulty, instructions)
VALUES
  ('Barbell Bench Press', 'A compound exercise that targets the chest, shoulders, and triceps', 'Strength', 'Chest', 'Barbell', 'Intermediate', 'Lie on a flat bench with feet on the ground. Grip the barbell slightly wider than shoulder width. Lower the bar to your chest, then press back up to starting position.'),
  ('Squat', 'A compound lower body exercise', 'Strength', 'Legs', 'Barbell', 'Intermediate', 'Stand with feet shoulder-width apart. Lower your body by bending your knees and hips, keeping your back straight. Return to standing position.'),
  ('Deadlift', 'A compound exercise that targets multiple muscle groups', 'Strength', 'Back', 'Barbell', 'Advanced', 'Stand with feet hip-width apart, barbell over midfoot. Bend at hips and knees to grip the bar. Lift the bar by extending hips and knees, keeping back straight.'),
  ('Pull-up', 'An upper body compound exercise', 'Strength', 'Back', 'Body weight', 'Intermediate', 'Hang from a pull-up bar with palms facing away. Pull your body up until chin is over the bar, then lower back to starting position.'),
  ('Push-up', 'A bodyweight exercise for the upper body', 'Strength', 'Chest', 'Body weight', 'Beginner', 'Start in plank position with hands slightly wider than shoulders. Lower your body until chest nearly touches the floor, then push back up.'),
  ('Dumbbell Shoulder Press', 'An upper body exercise for shoulder development', 'Strength', 'Shoulders', 'Dumbbells', 'Intermediate', 'Sit or stand with dumbbells at shoulder height. Press the weights overhead until arms are extended, then lower back to starting position.'),
  ('Barbell Row', 'A compound back exercise', 'Strength', 'Back', 'Barbell', 'Intermediate', 'Bend at hips with slight knee bend, back flat. Grip barbell with hands shoulder-width apart. Pull bar to lower chest, then lower back down with control.'),
  ('Lunges', 'A unilateral lower body exercise', 'Strength', 'Legs', 'Body weight', 'Beginner', 'Stand with feet hip-width apart. Step forward with one leg and lower body until both knees are bent at 90 degrees. Return to starting position and repeat with other leg.'),
  ('Plank', 'A core stabilization exercise', 'Core', 'Abs', 'Body weight', 'Beginner', 'Start in push-up position with forearms on the ground. Keep body in straight line from head to heels, engaging core muscles. Hold position.'),
  ('Bicep Curl', 'An isolation exercise for the biceps', 'Strength', 'Arms', 'Dumbbells', 'Beginner', 'Stand with dumbbells in hand, arms extended. Curl weights toward shoulders while keeping elbows close to body. Lower back to starting position.'),
  ('Tricep Dip', 'An isolation exercise for the triceps', 'Strength', 'Arms', 'Body weight', 'Intermediate', 'Sit on edge of bench or chair with hands gripping edge. Slide buttocks off bench and lower body by bending elbows. Push back up to starting position.'),
  ('Leg Press', 'A machine-based lower body exercise', 'Strength', 'Legs', 'Machine', 'Beginner', 'Sit in leg press machine with feet on platform. Release safety and lower platform by bending knees. Push platform away by extending legs.'),
  ('Lat Pulldown', 'A machine-based back exercise', 'Strength', 'Back', 'Machine', 'Beginner', 'Sit at lat pulldown machine with thighs secured. Grip bar with hands wider than shoulders. Pull bar down to upper chest, then slowly return to starting position.'),
  ('Russian Twist', 'A rotational core exercise', 'Core', 'Abs', 'Body weight', 'Intermediate', 'Sit on floor with knees bent and feet elevated. Lean back slightly, keeping back straight. Rotate torso to one side, then the other.'),
  ('Mountain Climber', 'A dynamic full-body exercise', 'Cardio', 'Full body', 'Body weight', 'Intermediate', 'Start in push-up position. Rapidly alternate bringing knees toward chest, as if running in place.'),
  ('Burpee', 'A high-intensity full-body exercise', 'Cardio', 'Full body', 'Body weight', 'Advanced', 'Start standing, then squat down and place hands on floor. Jump feet back to plank position, perform a push-up, jump feet forward, then explosively jump up with arms overhead.'),
  ('Jumping Jack', 'A classic cardio exercise', 'Cardio', 'Full body', 'Body weight', 'Beginner', 'Stand with feet together and arms at sides. Jump feet out to sides while raising arms overhead, then jump back to starting position.'),
  ('Dumbbell Lunge', 'A weighted variation of the lunge', 'Strength', 'Legs', 'Dumbbells', 'Intermediate', 'Hold dumbbells at sides. Step forward with one leg and lower body until both knees are bent at 90 degrees. Return to starting position and repeat with other leg.'),
  ('Kettlebell Swing', 'A dynamic hip-hinge exercise', 'Strength', 'Full body', 'Kettlebell', 'Intermediate', 'Stand with feet shoulder-width apart, kettlebell on floor between feet. Hinge at hips to grip kettlebell with both hands. Swing kettlebell between legs, then forcefully extend hips to swing kettlebell to chest height.'),
  ('Box Jump', 'A plyometric lower body exercise', 'Plyometric', 'Legs', 'Box', 'Intermediate', 'Stand facing box with feet shoulder-width apart. Lower into quarter squat, then explosively jump onto box, landing softly with knees bent. Step back down and repeat.');